/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type TradeStruct = {
  seller: AddressLike;
  buyer: AddressLike;
  cryptoAmount: BigNumberish;
  buyerCollateral: BigNumberish;
  privacyHashedBankDetails: BytesLike;
  status: BigNumberish;
  createdAt: BigNumberish;
  fundedAt: BigNumberish;
  fiatSentAt: BigNumberish;
  proofId: BytesLike;
};

export type TradeStructOutput = [
  seller: string,
  buyer: string,
  cryptoAmount: bigint,
  buyerCollateral: bigint,
  privacyHashedBankDetails: string,
  status: bigint,
  createdAt: bigint,
  fundedAt: bigint,
  fiatSentAt: bigint,
  proofId: string
] & {
  seller: string;
  buyer: string;
  cryptoAmount: bigint;
  buyerCollateral: bigint;
  privacyHashedBankDetails: string;
  status: bigint;
  createdAt: bigint;
  fundedAt: bigint;
  fiatSentAt: bigint;
  proofId: string;
};

export interface ArcP2PEscrowServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_FEE_BPS"
      | "DISPUTE_WINDOW"
      | "MAX_FEE_BPS"
      | "RELEASE_TIMEOUT"
      | "SLASH_AMOUNT"
      | "calculateNetRelease"
      | "feeBps"
      | "fundBuyerCollateral"
      | "getTrade"
      | "initiateTrade"
      | "markFiatSent"
      | "nextTradeId"
      | "oracleAddress"
      | "oracleRelease"
      | "oracleResolveDispute"
      | "owner"
      | "raiseDispute"
      | "reclaimExpiredTrade"
      | "releaseFunds"
      | "setFee"
      | "setOracle"
      | "setTreasury"
      | "trades"
      | "transferOwnership"
      | "treasuryWallet"
      | "usdc"
      | "usedProofIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "FiatSentMarked"
      | "OracleProofSubmitted"
      | "OracleUpdated"
      | "TradeCompleted"
      | "TradeDisputed"
      | "TradeFunded"
      | "TradeInitiated"
      | "TradeResolved"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELEASE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNetRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundBuyerCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTrade",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markFiatSent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTradeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleRelease",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleResolveDispute",
    values: [BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimExpiredTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usedProofIds",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELEASE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateNetRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundBuyerCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markFiatSent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleResolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclaimExpiredTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedProofIds",
    data: BytesLike
  ): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newBps: BigNumberish];
  export type OutputTuple = [newBps: bigint];
  export interface OutputObject {
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FiatSentMarkedEvent {
  export type InputTuple = [tradeId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [tradeId: bigint, buyer: string];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleProofSubmittedEvent {
  export type InputTuple = [tradeId: BigNumberish, proofId: BytesLike];
  export type OutputTuple = [tradeId: bigint, proofId: string];
  export interface OutputObject {
    tradeId: bigint;
    proofId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [newOracle: AddressLike];
  export type OutputTuple = [newOracle: string];
  export interface OutputObject {
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCompletedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    amountAfterFee: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    amountAfterFee: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    amountAfterFee: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeDisputedEvent {
  export type InputTuple = [tradeId: BigNumberish, raisedBy: AddressLike];
  export type OutputTuple = [tradeId: bigint, raisedBy: string];
  export interface OutputObject {
    tradeId: bigint;
    raisedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeFundedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    buyerCollateral: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    buyerCollateral: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    buyerCollateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeInitiatedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    seller: AddressLike,
    cryptoAmount: BigNumberish,
    hashedBankDetails: BytesLike
  ];
  export type OutputTuple = [
    tradeId: bigint,
    seller: string,
    cryptoAmount: bigint,
    hashedBankDetails: string
  ];
  export interface OutputObject {
    tradeId: bigint;
    seller: string;
    cryptoAmount: bigint;
    hashedBankDetails: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeResolvedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    winner: AddressLike,
    buyerSlashed: boolean
  ];
  export type OutputTuple = [
    tradeId: bigint,
    winner: string,
    buyerSlashed: boolean
  ];
  export interface OutputObject {
    tradeId: bigint;
    winner: string;
    buyerSlashed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcP2PEscrowService extends BaseContract {
  connect(runner?: ContractRunner | null): ArcP2PEscrowService;
  waitForDeployment(): Promise<this>;

  interface: ArcP2PEscrowServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  RELEASE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  SLASH_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  calculateNetRelease: TypedContractMethod<
    [_tradeId: BigNumberish],
    [[bigint, bigint] & { buyerReceives: bigint; platformFee: bigint }],
    "view"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  fundBuyerCollateral: TypedContractMethod<
    [_tradeId: BigNumberish, _collateral: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTrade: TypedContractMethod<
    [_tradeId: BigNumberish],
    [TradeStructOutput],
    "view"
  >;

  initiateTrade: TypedContractMethod<
    [_cryptoAmount: BigNumberish, _hashedBankDetails: BytesLike],
    [bigint],
    "nonpayable"
  >;

  markFiatSent: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextTradeId: TypedContractMethod<[], [bigint], "view">;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  oracleRelease: TypedContractMethod<
    [_tradeId: BigNumberish, _proofId: BytesLike],
    [void],
    "nonpayable"
  >;

  oracleResolveDispute: TypedContractMethod<
    [_tradeId: BigNumberish, _favourBuyer: boolean, _proofId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  reclaimExpiredTrade: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseFunds: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setOracle: TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        seller: string;
        buyer: string;
        cryptoAmount: bigint;
        buyerCollateral: bigint;
        privacyHashedBankDetails: string;
        status: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        fiatSentAt: bigint;
        proofId: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryWallet: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  usedProofIds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELEASE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateNetRelease"
  ): TypedContractMethod<
    [_tradeId: BigNumberish],
    [[bigint, bigint] & { buyerReceives: bigint; platformFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundBuyerCollateral"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, _collateral: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTrade"
  ): TypedContractMethod<[_tradeId: BigNumberish], [TradeStructOutput], "view">;
  getFunction(
    nameOrSignature: "initiateTrade"
  ): TypedContractMethod<
    [_cryptoAmount: BigNumberish, _hashedBankDetails: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markFiatSent"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextTradeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracleRelease"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, _proofId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracleResolveDispute"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, _favourBuyer: boolean, _proofId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reclaimExpiredTrade"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        seller: string;
        buyer: string;
        cryptoAmount: bigint;
        buyerCollateral: bigint;
        privacyHashedBankDetails: string;
        status: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        fiatSentAt: bigint;
        proofId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usedProofIds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FiatSentMarked"
  ): TypedContractEvent<
    FiatSentMarkedEvent.InputTuple,
    FiatSentMarkedEvent.OutputTuple,
    FiatSentMarkedEvent.OutputObject
  >;
  getEvent(
    key: "OracleProofSubmitted"
  ): TypedContractEvent<
    OracleProofSubmittedEvent.InputTuple,
    OracleProofSubmittedEvent.OutputTuple,
    OracleProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeCompleted"
  ): TypedContractEvent<
    TradeCompletedEvent.InputTuple,
    TradeCompletedEvent.OutputTuple,
    TradeCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TradeDisputed"
  ): TypedContractEvent<
    TradeDisputedEvent.InputTuple,
    TradeDisputedEvent.OutputTuple,
    TradeDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TradeFunded"
  ): TypedContractEvent<
    TradeFundedEvent.InputTuple,
    TradeFundedEvent.OutputTuple,
    TradeFundedEvent.OutputObject
  >;
  getEvent(
    key: "TradeInitiated"
  ): TypedContractEvent<
    TradeInitiatedEvent.InputTuple,
    TradeInitiatedEvent.OutputTuple,
    TradeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeResolved"
  ): TypedContractEvent<
    TradeResolvedEvent.InputTuple,
    TradeResolvedEvent.OutputTuple,
    TradeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint16)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "FiatSentMarked(uint256,address)": TypedContractEvent<
      FiatSentMarkedEvent.InputTuple,
      FiatSentMarkedEvent.OutputTuple,
      FiatSentMarkedEvent.OutputObject
    >;
    FiatSentMarked: TypedContractEvent<
      FiatSentMarkedEvent.InputTuple,
      FiatSentMarkedEvent.OutputTuple,
      FiatSentMarkedEvent.OutputObject
    >;

    "OracleProofSubmitted(uint256,bytes32)": TypedContractEvent<
      OracleProofSubmittedEvent.InputTuple,
      OracleProofSubmittedEvent.OutputTuple,
      OracleProofSubmittedEvent.OutputObject
    >;
    OracleProofSubmitted: TypedContractEvent<
      OracleProofSubmittedEvent.InputTuple,
      OracleProofSubmittedEvent.OutputTuple,
      OracleProofSubmittedEvent.OutputObject
    >;

    "OracleUpdated(address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "TradeCompleted(uint256,address,uint256,uint256)": TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;
    TradeCompleted: TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;

    "TradeDisputed(uint256,address)": TypedContractEvent<
      TradeDisputedEvent.InputTuple,
      TradeDisputedEvent.OutputTuple,
      TradeDisputedEvent.OutputObject
    >;
    TradeDisputed: TypedContractEvent<
      TradeDisputedEvent.InputTuple,
      TradeDisputedEvent.OutputTuple,
      TradeDisputedEvent.OutputObject
    >;

    "TradeFunded(uint256,address,uint256)": TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;
    TradeFunded: TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;

    "TradeInitiated(uint256,address,uint256,bytes32)": TypedContractEvent<
      TradeInitiatedEvent.InputTuple,
      TradeInitiatedEvent.OutputTuple,
      TradeInitiatedEvent.OutputObject
    >;
    TradeInitiated: TypedContractEvent<
      TradeInitiatedEvent.InputTuple,
      TradeInitiatedEvent.OutputTuple,
      TradeInitiatedEvent.OutputObject
    >;

    "TradeResolved(uint256,address,bool)": TypedContractEvent<
      TradeResolvedEvent.InputTuple,
      TradeResolvedEvent.OutputTuple,
      TradeResolvedEvent.OutputObject
    >;
    TradeResolved: TypedContractEvent<
      TradeResolvedEvent.InputTuple,
      TradeResolvedEvent.OutputTuple,
      TradeResolvedEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
